### PR TITLE
Add ESP32S3 STL

### PR DESCRIPTION
**Pull request by XyDrive**
4 Stl for box, top, and inter racks.

### CODE REVIEW

**Comment by andreock** [comment]
Great design, I really like it. Thank you for the contribution!

**Comment by andreock** [comment]
This case is intended for used with PCB provided in this repository or not? Just to specify in docs

**Comment by XyDrive** [comment]
nop, i'll create a doc to explain how to build the capibara with this case. 
But i can create a variant compatible with  [This](https://github.com/CapibaraZero/resources/tree/main/PCB/ESP32-S3-DEVKITC-1) PCB. But i need some time to order it and built it.

**Comment by andreock** [comment]
It would be great but is not a big problem for the moment, Take your time. However I am considering deprecating PCBs because all components soldered allows you to save a lot of space, or maybe to use a stripboard

**Comment by andreock** [comment]
I confirm, PCB will deprecated when I will make another case for Arduino Nano ESP32

**Comment by XyDrive** [comment]
ok good to know.
And I wanted to say that i could always personally help people who would like to print the box while I do the documentation. 
And I'm not going to do it immediately. I've got my exams coming up very soon and I've got more and more work to do for my studies.
I've set myself a deadline and it will be done by 10 February at the latest. Is it good for you ?

**Comment by andreock** [comment]
Sure no problems. I will slow down the development this month, I have to do my exams in January also.

**Comment by andreock** [comment]
Hi! @XyDrive I finally printed your box and I really like the design, I figured out where to put the IR modules, however I don't understand where the SD, the charger and the SX1276 go. Could you tell me, if you have time, how to put these two modules? Thank you

**Comment by XyDrive** [comment]
Hey thnks.
I know i will do tuto to how to build it.
I'm sorry i'm not at my home but there is a little illustration

**Comment by andreock** [comment]
Ok, thanks. I created a mock page for your box in the official documentation, you can find it in `latest` branch undex `docs/boards/box/Box.md`. When you have time, use that page for documentation. There is no hurry, take it easy. Thank you very much

**Pull request merged**
